spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://132.72.65.120:3306/soccer_sys_db?serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/soccer_sys_db?serverTimezone=UTC
    username: root
    password: iris123
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true
    show-sql: true